services:
  umami-proxy:
    image: ghcr.io/qaduni/umami-proxy:latest
    pull_policy: always
    restart: always
    expose:
      - "8080"
    environment:
      - UMAMI_URL=${UMAMI_URL}
      - UMAMI_API_KEY=${UMAMI_API_KEY}